apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hooks-demo
  namespace: argocd
spec:
  project: team-demo
  source:
    repoURL: https://github.com/claudioaddobbatim2r2/esercizio8.git
    targetRevision: main
    path: hooks-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: hooks-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true