apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/claudioaddobbatim2r2/esercizio89.git
    targetRevision: main
    path: sync-waves-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: waves-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true