apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-demo
  namespace: argocd
spec:
  description: Progetto con permessi limitati per l'esercizio RBAC
  sourceRepos:
    - https://github.com/claudioaddobbatim2r2/esercizio8.git
  destinations:
    - namespace: hooks-demo
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace