apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-demo
  template:
    metadata:
      labels:
        app: ci-demo
    spec:
      containers:
        - name: web
          image: claudioadd/ci-demo:93d8275
          ports:
            - containerPort: 80